#!/usr/bin/sh
clear
echo "This is an example project for working with CUDA and NVIDIA GPU. It should be used for learning purposes and early experiments."
echo ""
echo "Building main.cu"
./build
echo ""
echo "The environment is ready."
echo "Execute './run' to start the application."
echo ""
zsh
